POST http://localhost:3004/users/
Content-Type:application/json

{
    "username":"dusasrinivas",
    "password":"dusasrinu@123"
}

###


POST http://localhost:3004/login/
Content-Type:application/json

{
    "username":"dusasrinivas",
    "password":"dusasrinu@123"
}

###

GET http://localhost:3000/fruits
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoaXZhIiwiaWF0IjoxNjcyMjA3Nzg2fQ.YhnQObq5o03Fj_S7t2tRuzl_4EoKqV678tVdYpf32TU

###

GET http://localhost:3000/fruits/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoaXZhIiwiaWF0IjoxNjcwOTA3ODUwfQ.kitJ-RO8eY-VBLPFnsB5iGwJA_xeeNJk1UPqoE54q7A
###

POST  http://localhost:3000/fruits
Content-type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoaXZhIiwiaWF0IjoxNjcwOTA3ODUwfQ.kitJ-RO8eY-VBLPFnsB5iGwJA_xeeNJk1UPqoE54q7A

{
    "fruitName":"guava"
}
###

PUT  http://localhost:3000/fruits/5
Content-type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoaXZhIiwiaWF0IjoxNjcwOTA3ODUwfQ.kitJ-RO8eY-VBLPFnsB5iGwJA_xeeNJk1UPqoE54q7A

{
    "fruitName":"jama"
}

###

DELETE  http://localhost:3000/fruits/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoaXZhIiwiaWF0IjoxNjcwOTA3ODUwfQ.kitJ-RO8eY-VBLPFnsB5iGwJA_xeeNJk1UPqoE54q7A

###

